[Team7_pair2] QnA 3단계 코드리뷰 부탁드립니다.
wwh-techcamp-2018/java-qna pull request #37
Opened 2018-07-10 09:23 UTC by serverwizard

코드리뷰 부탁드립니다.

2018-07-10 12:35 UTC, javajigi requested changes
벌써 답변까지 구현하다니. 너무 빠른 것 아닌가요? ㅋㅋ
구현 잘 했네요. 👍

2018-07-10 12:35 UTC, javajigi commented on src/main/java/codesquad/domain/Answer.java
> +public class Answer {
답변에 작성자가 있어야 하지 않을까?
그런데 벌써 답변까지..

2018-07-10 12:35 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
> +    public void setAnswers(List<Answer> answers) {
createAnswer 메소드가 있는데 굳이 이 메소드도 필요한가?

2018-07-10 12:35 UTC, javajigi commented on src/main/java/codesquad/service/AnswerService.java
> +        answerRepository.save(newAnswer);
명시적으로 answerRepository.save(newAnswer)와 같이 구현하지 않아도 답변이 추가되는지 확인해 본다.
newAnswer.setQuestion(savedQuestion) 구현을 savedQuestion.createAnswer() 메소드에서 구현해 본다.

2018-07-10 12:35 UTC, javajigi commented on src/main/java/codesquad/web/QuestionController.java
> +        User loginUser = (User) SessionUtils.getSessionedUser(session);
굳이 매번 User로 캐스팅해야 되나? getSessionedUser()에서 캐스팅한 User를 반환하는 것은?

2018-07-10 12:41 UTC, serverwizard commented on src/main/java/codesquad/domain/Answer.java
> +public class Answer {
아직 답변 기능이 완전치 않은 상태인데 감사합니다!

2018-07-11 05:54 UTC, javajigi requested changes
구현 잘 했네요. 피드백 남겼어요.

2018-07-11 05:54 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
>      }
이 메소드의 경우 많은 로직을 포함하고 있는데 단위 테스트가 있으면 어떨까?

2018-07-11 05:54 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
> +        }
이 로직을 answer.delete()에서 처리하면 되지 않을까?

2018-07-11 09:35 UTC, merged