[Team1_pair2] Implements qna step4
wwh-techcamp-2018/java-qna pull request #43
Opened 2018-07-11 05:53 UTC by doooyeon

2018-07-11 08:16 UTC, javajigi requested changes
구현 잘 했네요. 👍 
피드백 남겼어요

2018-07-11 08:16 UTC, javajigi commented on src/main/java/codesquad/domain/Answer.java
> +
답변에 대한 삭제 기능을 이곳에 구현하는 것은 어떤가?

2018-07-11 08:16 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
> +    }
question.delete(loginUser)

위와 같은 구조로 question이 삭제 처리를 담당하는 것은 어떨까?

2018-07-11 08:51 UTC, merged

2018-07-12 11:54 UTC, minsungryu commented on src/main/java/codesquad/domain/Answer.java
>      @OneToOne
Answer와 User의 관계는 @ManyToOne 아닐까요??