qna step4 구현
wwh-techcamp-2018/java-qna pull request #49
Opened 2018-07-11 10:52 UTC by Kelicia91

코드리뷰 부탁드립니다.

2018-07-11 11:46 UTC, javajigi requested changes
단위 테스트 추가 잘 했네요. 👍 
피드백 몇 개 남겨요

2018-07-11 11:46 UTC, javajigi commented on src/main/java/codesquad/domain/Answer.java
> +
답변을 삭제하는 메소드가 Answer에 있으면 어떨까요?
답변 삭제 가능 여부에 대한 판단도 이 메소드에 처리하면 어떨까요?
answer.delete(loginUser);

2018-07-11 11:46 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
> +    public void delete() {
이 메소드에서 삭제 가능 여부도 판단하면 어떨까?
question.delete(loginUser);

2018-07-12 01:06 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
> +    public void delete() {
2팀에 달았던 댓글인데 복붙해서 넣습니다 ㅎㅎ

이 부분은 저도 교육받을 때 포비님이 자주 리뷰해주시던 부분인데,
당시에는 도메인은 getter, setter 등만 구현하고 검증부분은 서비스 레벨에서 책임이 있다고 생각해서
왜 delete나 update에 검증로직을 넣는걸 좋아하실까... 라고 생각하였으나
(뭔가 도메인은 값만 들고 있고 비즈니스로직은 서비스에서 하는 것이 맞지 않는가... 라는 생각이었죠)
지금 보니 도메인레벨에서 검증로직을 넣는 것도 좋아보이네요.

개인정보 update나 delete는 매우 민감한 부분이어서 실수로 지워지거나 덮어쓰게 되면 안되기 때문에...
검증로직이 항상 필요한 경우가 대부분인데요.
이걸 도메인에서 구현하게 되면 실수가 일어날 가능성이 확 떨어질 것 같습니다.

제가 만든 도메인을 다른 개발자 분들이 가져다 쓸 수도 있는 것이기 때문에,
도메인에 미리 방어를 해두면 무책임한 서비스로직에 대한 방어가 더 잘 될 것이라고 생각합니당.
휴먼 에러가 발생할 여지를 얼마나 줄일 수 있는가, 가 관건인 것 같아요.

2018-07-12 08:33 UTC, merged

2018-07-12 11:20 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/Question.java
> +    public void delete() {
감사합니다! ㅎㅎ

2018-07-12 12:55 UTC, minsungryu commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
강의시간에 언급된 것처럼 `FetchType.LAZY`가 더 좋지 않을까요?

2018-07-12 14:14 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
이 경우엔 FetchType.EAGER가 더 좋을 것 같습니다. 
OneToMany 관계에서 EAGER로 설정하면 Question객체를 가져올 때 answers를 join해서 하나의 쿼리로 가져오지만 
LAZY로 할 경우 Question객체를 하나의 쿼리로 먼저 가져오고 나중에 answer가 필요할 때 각각의 answer를 불러오게 됩니당. 
N + 1 쿼리 문제라고 하는데 자세한 내용은 
http://jojoldu.tistory.com/165 요 블로그를 참조하세요!

2018-07-12 14:48 UTC, Kelicia91 commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
헉.. 현업도 바쁘실텐데 늦은 시간까지 리뷰해주셔서 감사합니다. 민성님도 리뷰 감사합니다 :-)

2018-07-12 15:09 UTC, minsungryu commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
@woowa-sehwankim 리뷰 감사합니다. 덕분에 N+1 문제에 대해 알게 되었네요.😀

그러나, 제가 이해하기로는 현재 미션에서 N+1 문제가 발생하지 않는다고 생각합니다.

블로그의 Test case를 보니, `FetchType.LAZY`일 때 모든 Academy(여기서 Question)에 대해 하위의 Subject(여기서 Answer)를 조회하기 때문에 N+1 문제가 발생한다고 보이는데요

현재 미션에서는 '/', '/questions'와 같은 주소에서 질문 목록만을 보여주고,
'/questions/1'에서 한 질문에 대한 답변 목록을 조회하기 때문입니다.
만약 N+1문제가 발생하려면, `FetchType.LAZY`일 때 질문 목록과 답변 목록을 한꺼번에 조회하는 경우가 아닐까 하는데요

포비와 다른 팀원분들은 어떻게 생각하시는지 궁금하네요

제가 잘못 이해하고 있는 부분이 있다면 코멘트 부탁드립니다 🙏

2018-07-13 00:03 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
하나의 Question에서 모든 Answer에 대해 접근할 때 발생할 것 같습니다. 
(사실 저도 JPA 알못이라 이랬는데 아니면 민망.. ㅋㅋ) 
가장 확실한건 JPA가 실행하는 쿼리를 눈으로 보는 거죠. 
application.yml (혹은 application.properties) 에 
```
jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
```
이런 식으로 옵션을 주시면 하이버네이트가 날리는 쿼리를 볼 수 있어요. 
한번 해보시고 쿼리를 몇개나 날리는지 알려주세요 ㅋㅋ (저도 궁금)

2018-07-13 03:47 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
이 경우에는 LAZY를 사용하는 더 적합합니다.
질문 목록의 경우 굳이 Answer가 필요없기 때문에 만약 EAGER로 설정하면 질문 목록에서 성능상 문제가 발생할 가능성이 높아집니다. @minsungryu 이 제대로 파악했네요.

2018-07-13 03:49 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
오우 노

2018-07-13 03:57 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
@woowa-sehwankim 
세환이 인턴에게 밀렸네. ㅋㅋ
굴하지 말고 앞으로도 리뷰 많이 해주세요. 덕분에 N+1 문제를 공부할 수 있는 계기가 됐잖아요.

2018-07-13 03:58 UTC, minsungryu commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
그렇군요ㅎㅎ 리뷰 감사합니다 😄

2018-07-13 03:58 UTC, hyukjin-lee commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
덕분에 많은 도움이 되었습니다 감사합니다!

2018-07-13 03:59 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
ㅋㅋ 그런데 사실 저는 구현 페이지가 그건 줄 알았어요. 
게시글 보여주고 밑에 댓글 쫙 나오는거 
게시글 리스트 찾고 있었군요(...)

2018-07-13 03:59 UTC, Kelicia91 commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
ㅎㅎ 모두 리뷰 달아주셔서 감사합니다. 덕분에 jojoldu님 블로그 또 방문하게 되었네요. 수정하겠습니다!

2018-07-13 04:00 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
오늘도 흥하는 동욱님의 블로그..

2018-07-13 04:43 UTC, booeh commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
조졸두가 아니라 조조 이동욱 이라는것만 알아주세여 :)

2018-07-13 04:44 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
> +    @OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
와 처음알았네요 조졸두가 아니었다니 (충격)