[team4 pair2] Step4 구현
wwh-techcamp-2018/java-qna pull request #51
Opened 2018-07-11 11:11 UTC by minsungryu

피드백 요청드립니다.

감사합니다 😀

2018-07-11 11:53 UTC, javajigi requested changes
객체지향 설계와 단위 테스트 연습을 위한 피드백 남겼어요.

2018-07-11 11:53 UTC, javajigi commented on src/main/java/codesquad/domain/Answer.java
> +        this.isDeleted = true;
👍

2018-07-11 11:53 UTC, javajigi commented on src/main/java/codesquad/domain/Question.java
질문 삭제 기능에 대한 요구사항을 다시 한번 파악해 보면 좋겠음다.
삭제 기능을 구현하고 삭제에 대한 판단 여부도 delete() 메소드 내에서 판단해보면 어떨까요?
question.delete(loginUser);

삭제 로직을 담당하는 경우의 수가 많은데 단위 테스트를 추가해 테스트해보면 어떨까요?

2018-07-12 01:02 UTC, woowa-sehwankim reviewed
지나가다가 남겨봅니당. 
포비님을 물리쳐주세요.

2018-07-12 01:02 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/User.java
> +    public boolean passwordMatch(String password) {
https://www.geeksforgeeks.org/java-naming-conventions/ 
자바 네이밍 컨벤션에서는 메소드의 이름은 **동사**로 짓도록 하고 있습니다. 
setName, getName이 동사로 시작하는 것처럼요.  
boolean 값을 리턴하는 메소드는 주로 is로 시작하는 네이밍을 많이 씁니다. 
isValidPassword 같은 이름도 좋을 것 같습니다. 

컨밴션도 한번 참고해주세요 ^__^

2018-07-12 01:02 UTC, woowa-sehwankim commented on src/main/java/codesquad/domain/Question.java
이 부분은 저도 교육받을 때 포비님이 자주 리뷰해주시던 부분인데, 
당시에는 도메인은 getter, setter 등만 구현하고 검증부분은 서비스 레벨에서 책임이 있다고 생각해서 
왜 delete나 update에 검증로직을 넣는걸 좋아하실까... 라고 생각하였으나 
(뭔가 도메인은 값만 들고 있고 비즈니스로직은 서비스에서 하는 것이 맞지 않는가... 라는 생각이었죠) 
지금 보니 도메인레벨에서 검증로직을 넣는 것도 좋아보이네요. 

개인정보 update나 delete는 매우 민감한 부분이어서 실수로 지워지거나 덮어쓰게 되면 안되기 때문에... 
검증로직이 항상 필요한 경우가 대부분인데요. 
이걸 도메인에서 구현하게 되면 실수가 일어날 가능성이 확 떨어질 것 같습니다. 

제가 만든 도메인을 다른 개발자 분들이 가져다 쓸 수도 있는 것이기 때문에, 
도메인에 미리 방어를 해두면 무책임한 서비스로직에 대한 방어가 더 잘 될 것이라고 생각합니당. 
휴먼 에러가 발생할 **여지**를 얼마나 줄일 수 있는가, 가 관건인 것 같아요.

2018-07-12 05:15 UTC, minsungryu commented on src/main/java/codesquad/domain/Question.java
@woowa-sehwankim 저희도 처음에 세환님과 비슷한 생각을 가지고 접근했으나.. 개발하다보니 도메인 영역에 검증하는 것이 필요하다는 것을 느꼈습니다. 피드백 해주신대로 고민해보고 개선하겠슴당!
@javajigi 좋은 가르침을 주시는데 제가 100% 다 흡수하지 못해서 많이 미흡하네요 😂

2018-07-12 11:04 UTC, javajigi commented
@woowa-sehwankim 여기서 어슬렁 가리지 말고 코드 리뷰나 좀 해요.

2018-07-12 11:06 UTC, javajigi commented
@woowa-sehwankim 오호. 코드 리뷰를 했군요. 앞으로 4팀은 리뷰 안할께요. 세환님은 하는 것으로 알고 있겠음다. ㅋㅋ

2018-07-12 11:06 UTC, merged

2018-07-12 11:26 UTC, minsungryu commented
@javajigi @woowa-sehwankim  😂😂😂두 분 모두 해주시면 너무 좋을 것 같아요!