[Team7_pair2] QnA 1단계 (DB없이 질문 기능)
wwh-techcamp-2018/java-qna pull request #9
Opened 2018-07-07 01:29 UTC by serverwizard

코드 리뷰 부탁드릴게요~

2018-07-07 02:25 UTC, javajigi requested changes
구현 잘 했네요. 불필요하게 구현하거나 객체지향 설계 관점에서 피드백 남겨요.

2018-07-07 02:25 UTC, javajigi commented on src/main/java/codesquad/web/QuestionController.java
> +        model.addAttribute("questions", questions);
model에 데이터 저장할 필요가 있을까?

2018-07-07 02:25 UTC, javajigi commented on src/main/java/codesquad/web/UserController.java
> +        users.set(id, user);
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

위 원칙에 따라 비밀번호 체크하는 로직을 user가 담당하면 어떨까?
savedUser.update(user);

2018-07-07 06:18 UTC, serverwizard commented on src/main/java/codesquad/web/UserController.java
> +        users.set(id, user);
포비(?)님, 피드백 주신 내용에서 한가지 궁금증이 있습니다. 피드백을 반영해 savedUser.update(user) 메소드 안에서 비밀번호 검사하는 부분을 넣었더니 Controller 단에서 비밀번호를 검사하는 코드의 중복이 제거되는 장점이 있을 것 같습니다. 하지만 객체에 메시지를 보내라는 원칙만 보자면 user.matchPassword(savedUser)도 메시지를 보내라는 원칙을 따랐다고 볼 수는 없는건가요?

2018-07-08 00:57 UTC, javajigi commented on src/main/java/codesquad/web/UserController.java
> +        users.set(id, user);
내 맞아요. 그 부분은 구현 잘 했고요.
그런데 비밀번호 체크하는 부분까지도 User가 담당하도록 구현하면 좋지 않을까라는 관점에서 피드백 남겼어요.

2018-07-08 01:19 UTC, merged

2018-07-08 04:43 UTC, serverwizard commented on src/main/java/codesquad/web/UserController.java
> +        users.set(id, user);
User 도메인 클래스에 대한 단위 테스트를 진행했다면, 당연히 비밀번호 체크하는 부분을 User가 담당하도록 구현했을텐데, 피드백 감사드립니다. 👍